// Emits /boot.js, a tiny classic script that index.html runs in <head> before the app's module
// loads, so the first paint already has the visitor's theme: page colours, color-scheme, the
// theme-color meta and the favicon. The CSP allows no inline script, so it is a same-origin file
// (served no-cache, see firebase.json). The theme table is baked in from themes.json.
//
// Vite loads its config, and so this file, with Node, so this imports only modules that import
// nothing themselves, by full file name. The default theme and the icon path repeat what
// stores/theme.ts and platform/head.ts say; vite-plugin-boot.test.ts keeps them in step.
import { readFileSync } from 'node:fs';
import type { Plugin } from 'vite';
import { colorSchemeFor } from '../src/lib/colour.ts';
import { STORAGE_KEYS } from '../src/services/storage-keys.ts';

export const BOOT_SCRIPT_FILE = 'boot.js';
export const DEFAULT_THEME = 'swamphen';
export const themeIconPath = (name: string): string => `/icons/theme/${name.toLowerCase()}.svg`;

interface ThemeColours {
  name: string;
  background: string;
  foreground: string;
  green: string;
}

function readThemes(): ThemeColours[] {
  return JSON.parse(readFileSync(new URL('../themes.json', import.meta.url), 'utf8')) as ThemeColours[];
}

/** What the boot script paints for one theme. */
export interface BootPaint {
  background: string;
  foreground: string;
  green: string;
  scheme: 'light' | 'dark';
  icon: string;
}

export function bootPaints(): Record<string, BootPaint> {
  return Object.fromEntries(
    readThemes().map((t) => [
      t.name,
      {
        background: t.background,
        foreground: t.foreground,
        green: t.green,
        scheme: colorSchemeFor(t.background),
        icon: themeIconPath(t.name),
      },
    ]),
  );
}

/** The script's source: ES5, so it runs in any WebView that can show the page at all. */
export function bootScript(): string {
  return `// Generated by scripts/vite-plugin-boot.ts from themes.json.
(function () {
  var themes = ${JSON.stringify(bootPaints())};
  var name = null;
  try {
    name = window.localStorage.getItem(${JSON.stringify(STORAGE_KEYS.theme.key)});
  } catch (e) {}
  var t = themes[Object.prototype.hasOwnProperty.call(themes, name) ? name : ${JSON.stringify(DEFAULT_THEME)}];
  var style = document.documentElement.style;
  style.backgroundColor = t.background;
  style.color = t.foreground;
  style.colorScheme = t.scheme;
  style.setProperty("--theme-background", t.background);
  style.setProperty("--theme-foreground", t.foreground);
  style.setProperty("--theme-green", t.green);
  var meta = document.querySelector('meta[name="theme-color"]');
  if (meta) meta.setAttribute("content", t.background);
  var icon = document.querySelector('link[rel~="icon"][type="image/svg+xml"]');
  if (icon) icon.setAttribute("href", t.icon);
})();
`;
}

export function bootScriptPlugin(): Plugin {
  return {
    name: 'vesen:boot-script',
    configureServer(server) {
      server.middlewares.use((req, res, next) => {
        if (req.url?.split('?')[0] !== `/${BOOT_SCRIPT_FILE}`) return next();
        res.setHeader('Content-Type', 'text/javascript; charset=utf-8');
        res.setHeader('Cache-Control', 'no-cache');
        res.end(bootScript());
      });
    },
    generateBundle() {
      this.emitFile({ type: 'asset', fileName: BOOT_SCRIPT_FILE, source: bootScript() });
    },
  };
}
