// Reflects the current theme onto the document: palette variables, the page colours behind the
// terminal, color-scheme, the theme-color meta that tints phone browser bars, and the favicon.
// public/boot.js (scripts/vite-plugin-boot.ts) paints the same colours before the app loads.
import type { Theme } from '../interfaces/theme';
import { colorSchemeFor } from '../lib/colour';

/** The favicon for a theme: one small SVG each, generated by scripts/icons.mjs. */
export function themeIconHref(name: string): string {
  return `/icons/theme/${name.toLowerCase()}.svg`;
}

export function applyTheme(doc: Document, theme: Theme): void {
  const root = doc.documentElement;
  // brightBlack becomes --theme-bright-black, cursorColor --theme-cursor-color, and so on.
  for (const [key, value] of Object.entries(theme)) {
    if (key !== 'name' && typeof value === 'string') {
      root.style.setProperty(`--theme-${key.replace(/[A-Z]/g, (c) => `-${c.toLowerCase()}`)}`, value);
    }
  }
  // The page itself, so the gutter around the terminal and any overscroll match the theme.
  root.style.backgroundColor = theme.background;
  root.style.color = theme.foreground;
  root.style.colorScheme = colorSchemeFor(theme.background);

  ensureElement(doc, 'meta[name="theme-color"]', () => {
    const meta = doc.createElement('meta');
    meta.setAttribute('name', 'theme-color');
    return meta;
  }).setAttribute('content', theme.background);

  // Only the SVG icon follows the theme; the PNG fallbacks stay on the default.
  const icon = ensureElement(doc, 'link[rel~="icon"][type="image/svg+xml"]', () => {
    const link = doc.createElement('link');
    link.setAttribute('rel', 'icon');
    link.setAttribute('type', 'image/svg+xml');
    link.setAttribute('sizes', 'any');
    return link;
  });
  const href = themeIconHref(theme.name);
  if (icon.getAttribute('href') !== href) icon.setAttribute('href', href);
}

/** The first element in <head> matching `selector`, created by `create` when there is none. */
function ensureElement(doc: Document, selector: string, create: () => Element): Element {
  const found = doc.head.querySelector(selector);
  if (found) return found;
  const created = create();
  doc.head.append(created);
  return created;
}
